### PR TITLE
Remove "inherits from webpack" from example

### LINKED ISSUE #7: options: "files" throwing errors when passed basic string input, unable to find app root directory
Hi there,

1. Running `stylelint '**/*.css'` in CLI works as expected. 
2. Configuring it through this package does not seem to get any matches. For all of the commented-out patterns I've tried (see the gist), I get:
`Error: Files glob patterns specified did not match any files`
3. The only exception to point 2 is '../../**/*.css'; this path begins to lint css in the `node_modules` folder. 
If I try to go one level up, I get:
 a `EISDIR: illegal operation on a directory, read`.
4. I get the same effect for all cases if I remove the `configBaseddir`, and `configFile` configuration properties.

This might be multiple separate errors. It looks like something is wrong with the way `files` is sending the glob pattern, and we're stuck searching for matches over contents of the `stylelint` folder, instead of the directory we want. In addition, when we go up enough levels, the plugin seems to be trying to access directories as files (point 4).

What do you think?
`webpack.config.js` below: 
https://gist.github.com/sdtsui/feb5f1de7c7c53e6e42180f201d890cd

Thanks!

p.s. for completeness, here is my `package.json`, with the `lint-css` script that works.
https://gist.github.com/sdtsui/a16a054228999f9150bb0fadc6f6d647
I'm on Node `v5.5.0`.

### PR DESCRIPTION
**Pull request by esseb**
See https://github.com/vieron/stylelint-webpack-plugin/issues/7#issuecomment-247270888

Resolves #7.

### CODE REVIEW

**Comment by JaKXz** [comment]
@esseb thanks for the PR! :) I'd still like to indicate somewhere that the default context is defined by webpack. Perhaps it would be clearer if the note was in `/* */` comments?

**Comment by JaKXz** [comment]
Well the point of this example is just to show the defaults `stylelint-webpack-plugin` provides. I think putting `webpack.compiler.context` would be a bit weird but would probably get the point across.

**Comment by esseb** [comment]
I didn't get that. What would you suggest the `// Default settings` section look like exactly?

**Comment by JaKXz** [comment]
@esseb it was easier to make my change directly than explain it :) hope that makes sense.

@vieron what do you think?

**Comment by esseb** [comment]
@JaKXz ah, looks great. Makes sense now, yes.

**Pull request merged**
