### PR TITLE
Restructuring with linting and coverage

### LINKED ISSUE #14: Update stylelint dependency
Current stylelint dependency is at `^6.0.1`, the latest stylelint version is `7.0.1`.

### PR DESCRIPTION
**Pull request by JaKXz**
Fixes #14.
Closes #15.

Hi @vieron, while writing #15 I was having some trouble debugging so I went a bit crazy and restructured things. I figured I should at least separate these things into different PRs so we can get the update/fix merged and published.

This might make for a good 1.0.0 so that you know where the coverage stands and so on.

EDIT: I'd definitely recommend _only squash-merging EITHER #15 or this._ Thanks!

### CODE REVIEW

**Comment by vieron** [comment]
Hi @JaKXz! 

Thank you very much for all the work! And sorry for the late response, I took some days off.

I'm in favour of merging this PR, but before that there is one thing I would like to change: Why removing `stylelint` from peerDependencies? 

My suggestion is to add it back with a semver range, like ` "stylelint": "^6.0.0 || ^7.0.0"`. As far as I've seen the breaking changes are all related with stylelint rules and not with the JavaScript API

What do you think? 

Thanks again!

**Comment by JaKXz** [comment]
@vieron no worries, glad you're back :)

I think removing `peerDependencies` is a good idea for two reasons:

1. It's "deprecated" in [npm v3](https://github.com/npm/npm/releases/tag/v3.0.0): meaning the specified modules aren't installed implicitly anyway. It seems like a reasonable requirement that if you have `stylelint-webpack-plugin` installed you must have `stylelint` installed as well.

2. Depending on `stylelint` v6 OR v7 is too much maintenance, because there are breaking changes between these versions... so we'd have to keep multiple versions of the `.stylelintrc` in the tests to make sure the API isn't throwing the wrong errors.

**Comment by vieron** [comment]
@JaKXz as you said `peerDependencies` is not deprecated, it just works different than before. Packages are not installed but you get a warning, which is good.

And regarding the second point, for me, it also applies when not specifying a stylelint version. You rely on any version the user has installed. It's like saying all versions are supported, but we just run test against v7.

I still think we should add the peerDependency, just depending in `^7.0.0` or in both `^6.0.0 || ^7.0.0`.

**Comment by JaKXz** [comment]
Fair enough, good point - I'll add it back and merge :)

**Comment by vieron** [comment]
Published `0.3.0` to npm :)

**Pull request merged**
