### PR TITLE
Update stylelint dependency

### LINKED ISSUE #14: Update stylelint dependency
Current stylelint dependency is at `^6.0.1`, the latest stylelint version is `7.0.1`.

### PR DESCRIPTION
**Pull request by JaKXz**
Fixes #14.

### CODE REVIEW

**Comment by sebinsua** [comment]
@JaKXz The tests seem to be failing. Any idea why?

**Comment by JaKXz** [comment]
@sebinsua because now the plugin code needs to be updated - feel free to take my commits and keep going, I'm very tied up atm unfortunately.

**Comment by JaKXz** [comment]
In fact, I'd vote for removing the `peerDependencies` stanza altogether since npm >=3 drops support for it. cc @vieron

**Comment by tcstory** [comment]
yeah , i met the problem,when i use "stylelint-config-standard": "^11.0.0", it will report the following error
Error: Undefined rule "media-feature-parentheses-space-inside"

**Pull request closed without merging**
